### PR TITLE
Upgraded to the latest sbt, Scala, dependencies, and openjdk base image

### PR DESCRIPTION
**Pull request by agemooij**
This project was using ancient, unsupported, end of life versions of sbt, Scala, Akka, and other libraries and an outdated openjdk base image.

I upgraded everything and made the required code changes to match the latest Scala standard libraries, Akka changes, etc. Slf4s has been dead for a long time and does not support Scala versions after 2.11. I replaced it with its successor.

### CODE REVIEW

**Comment by agemooij** [comment]
Tested on the test environment in K8s. Not a single unit test available unfortunately.

**Comment by agemooij** [comment]
I also added scalafmt with the same config as used on agent-scorecard, which of course resulted in 24 files being reformated. I did it in a separate commit so you can review the two major changes individually by looking at the individual commits

**Comment by gwena** [comment]
Thanks a lot @agemooij . This service is the most outdated of all, and with your changes, will be the most up to date (Scala, sbt, dependencies, docker image).
Yes,  unfortunately no tests. When deployed in TEST, we should use for a few days, check logs, etc. Not sure if you have a different approach, but this service is the entry points for all our API so we should rather not rush the push to PROD.

**Comment by agemooij** [comment]
Agreed. It is running in `test` since last evening so by Monday we should have a good sense of stability

**Comment by agemooij** [comment]
I'll rebase this PR now that the other one has been merged

**Pull request merged**
